import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import styles from "../styles/Home.module.css"
import HeaderComp from "../components/headerComp"
import { useState, useEffect, useRef } from 'react';

export default function Home() {

  const [index, setIndex] = useState(0);

  const home = useRef(null);
  const about = useRef(null);
  const projects = useRef(null);
  const experience = useRef(null);

  const sections = [home, about, projects, experience];

  useEffect(() => {
    const handleKeyDown = (event) => {
      if (event.key === 'ArrowUp') {
        setIndex(index => Math.max(0, index - 1));
        event.preventDefault();
        scrollToSection(sections[index > 0 ? index - 1 : 0]);
      } else if (event.key === 'ArrowDown') {
        setIndex(index => Math.min(sections.length - 1, index + 1));
        event.preventDefault();
        scrollToSection(sections[index < sections.length - 1 ? index + 1 : sections.length - 1]);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [index, sections]);

  const scrollToSection = (elementRef) => {
    window.scrollTo({
      top: elementRef.current.offsetTop,
      behavior: "smooth",
    });
  };

  const sectionData = [
    { title: "Home", description: "Welcome to my homepage.", image: "/home-image.jpg", url: "/" },
    { title: "About", description: "Learn more about me.", image: "/about-image.jpg", url: "/about" },
    { title: "Projects", description: "Check out my projects.", image: "/projects-image.jpg", url: "/projects" },
    { title: "Experience", description: "My professional experience.", image: "/experience-image.jpg", url: "/experience" },
  ];

  return (
    <div className={styles.container}>

      <Head>
        <title>Max Lee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" />
      </Head>

      <div ref={home}>
        <HeaderComp 
          title={sectionData[0].title}
          description={sectionData[0].description}
          image={sectionData[0].image}
          url={sectionData[0].url}
        />
      </div>

      <div ref={about}>
        <HeaderComp 
          title={sectionData[1].title}
          description={sectionData[1].description}
          image={sectionData[1].image}
          url={sectionData[1].url}
        />
      </div>

      <div ref={projects}>
        <HeaderComp 
          title={sectionData[2].title}
          description={sectionData[2].description}
          image={sectionData[2].image}
          url={sectionData[2].url}
        />
      </div>

      <div ref={experience}>
        <HeaderComp 
          title={sectionData[3].title}
          description={sectionData[3].description}
          image={sectionData[3].image}
          url={sectionData[3].url}
        />
      </div>

    </div>
  );
}
